### ISSUE TITLE
Feature request: Add download size to data overview

### ISSUE THREAD

**Issue by kd-ods** [openownership/bodsdata#1]
If it were relatively easy to do, then having the file size next to the CSV, SQLite download etc would be useful:

![image](https://user-images.githubusercontent.com/35495305/161709948-a9f3bc71-f0cd-4a41-8d90-0e1a57c4e5e7.png)

**Comment by StephenAbbott** [comment]
Feature introduced by https://github.com/openownership/bodsdata/pull/13
