### ISSUE TITLE
New output: XLSX in multithreaded mode

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/bodsdata#8]
https://github.com/kindly/flatterer/releases/tag/v0.13.1

**Comment by StephenAbbott** [comment]
Recent call highlighted that Uganda's FIU uses Excel for its data analysis work so see if we can highlight this with them after work done

**Comment by StephenAbbott** [comment]
@kindly @lgs85 Could you add a summary of thinking here about why it was best not to pursue XLSX format?

**Comment by lgs85** [comment]
@StephenAbbott I think that the main reason is that most registers will be too large to be able to open and analyse in excel, so we'd be in a slightly clunky situation of making it available only for the very small sources. I'll let @kindly expand if he has anything further to add.

**Comment by kindly** [comment]
@StephenAbbott @lgs85  yes most sources the xlsx output would be too big.  Also, even if it can technically fit into excel too much data makes it practially unusable, especially if used in other spreadsheets like google sheets or libreoffice which deal very badly with bigger data compared to MS Excel.  My worry is that the experiance would just be bad for most cases. Slovakia of the current sources would be the only one that would be fine.

It would be fairly simple to add if we knew what the reasonable contraints were, but it would be limited to fairly small sources.  

As a side note the soon to be released Open Contracting Register will most likely use flatterer and I think they are applying some limit to the xlsx output, which would be good to see, however they have a lot of smaller sources.

**Comment by StephenAbbott** [comment]
Thanks @kindly. Thought that this issue was just the output was too big for xlsx but wanted to make sure.

You're the second person who has mentioned the upcoming Open Contracting Register today. If you have any details on that, could you forward them to me on email? Would be great to know when this is launching
